/**
 * scripts/sync-env.mjs
 *
 * Single source of environment configuration lives at the repo root
 * (`.env` + `.env.local`). Next.js requires env vars visible from each
 * application directory, so this script materialises a small,
 * NON-SECRET slice of the root config into each app's `.env.local`.
 *
 * Only these variables are copied:
 *   - every var prefixed with `NEXT_PUBLIC_`
 *   - `API_BASE_URL` (used by Next server-side code, not a secret)
 *   - `ROOT_DOMAIN` (used by Next server-side proxy code, not a secret)
 *
 * Secrets (MONGODB_URI, JWT_*, COOKIE_SECRET, SUPER_ADMIN_PASSWORD, ...)
 * are NEVER copied into the apps and can never reach the browser.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

function parseEnvFile(file) {
  const map = new Map();
  let content;
  try {
    content = readFileSync(file, 'utf8');
  } catch {
    return map;
  }
  const lines = content.split(/\r?\n/);
  for (const raw of lines) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    // expand later-composed keys (LOCAL overrides base)
    map.set(key, value);
  }
  return map;
}

const base = parseEnvFile(join(root, '.env'));
const local = parseEnvFile(join(root, '.env.local'));
const merged = new Map([...base, ...local]);

const allowedPrefixes = ['NEXT_PUBLIC_'];
const allowedExact = ['API_BASE_URL', 'ROOT_DOMAIN'];

const lines = [];
for (const [key, value] of merged) {
  const ok = allowedPrefixes.some((p) => key.startsWith(p)) || allowedExact.includes(key);
  if (ok) lines.push(`${key}=${value}`);
}
lines.sort();
lines.unshift('# Auto-generated by scripts/sync-env.mjs from the root .env / .env.local');
lines.push('');

for (const app of ['web', 'admin', 'super-admin', 'api']) {
  const target = join(root, 'apps', app, '.env.local');
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, lines.join('\n'));
  console.log(`[env:sync] wrote ${target}`);
}